# Downloads everything the game used to load from the internet, so it runs offline
# (needed for the store apps):
#   - three.js r128 and cannon.js 0.6.2 from cdnjs  -> js/vendor/  (checked against cdnjs SRI hashes)
#   - Google Fonts, cut down to only the characters the game uses -> assets/fonts/ + css/fonts.css
#
# Re-run this whenever you add new text (new characters) to index.html / js/main.js / js/ads.js / css/style.css.
# Usage: powershell -ExecutionPolicy Bypass -File tools\offline\fetch-offline.ps1
$ErrorActionPreference = 'Stop'
$root = (Resolve-Path (Join-Path $PSScriptRoot '..\..')).Path
$utf8 = New-Object System.Text.UTF8Encoding($false)
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12

# ---------- JS libraries ----------
$vendor = Join-Path $root 'js\vendor'
New-Item -ItemType Directory -Force $vendor | Out-Null
$libs = @(
  @{ lib = 'three.js';  ver = 'r128';  file = 'three.min.js' },
  @{ lib = 'cannon.js'; ver = '0.6.2'; file = 'cannon.min.js' }
)
foreach ($l in $libs) {
  $out = Join-Path $vendor $l.file
  Invoke-WebRequest "https://cdnjs.cloudflare.com/ajax/libs/$($l.lib)/$($l.ver)/$($l.file)" -OutFile $out -UseBasicParsing
  $sri = (Invoke-RestMethod "https://api.cdnjs.com/libraries/$($l.lib)/$($l.ver)?fields=sri").sri.($l.file)
  $sha = [Security.Cryptography.SHA512]::Create()
  $actual = 'sha512-' + [Convert]::ToBase64String($sha.ComputeHash([IO.File]::ReadAllBytes($out)))
  if ($actual -ne $sri) { throw "$($l.file): hash mismatch (expected $sri, got $actual)" }
  Write-Host "ok  js/vendor/$($l.file)  $((Get-Item $out).Length) bytes, SRI verified"
}

# ---------- characters used by the game ----------
$set = New-Object 'System.Collections.Generic.SortedSet[int]'
for ($c = 0x20; $c -le 0x7E; $c++) { [void]$set.Add($c) }
# always include kana, full-width digits/letters and common punctuation (for numbers and future text)
foreach ($r in @(@(0x3000,0x303F), @(0x3041,0x3096), @(0x309B,0x309F), @(0x30A0,0x30FF), @(0xFF01,0xFF5E))) {
  for ($c = $r[0]; $c -le $r[1]; $c++) { [void]$set.Add($c) }
}
foreach ($f in 'index.html', 'js\main.js', 'js\ads.js', 'css\style.css') {
  $text = [IO.File]::ReadAllText((Join-Path $root $f), $utf8)
  foreach ($ch in $text.ToCharArray()) {
    $c = [int]$ch
    # skip ASCII (already added), controls, surrogates (emoji use the system font) and variation selectors
    if ($c -lt 0x80 -or ($c -ge 0xD800 -and $c -le 0xDFFF) -or ($c -ge 0xFE00 -and $c -le 0xFE0F)) { continue }
    [void]$set.Add($c)
  }
}
$chars = @($set)
Write-Host "characters: $($chars.Count)"

# ---------- fonts ----------
$fontDir = Join-Path $root 'assets\fonts'
if (Test-Path $fontDir) { Remove-Item (Join-Path $fontDir '*.woff2') }
New-Item -ItemType Directory -Force $fontDir | Out-Null
$fonts = @(
  @{ family = 'Zen Maru Gothic'; weight = 500 },
  @{ family = 'Zen Maru Gothic'; weight = 700 },
  @{ family = 'Zen Maru Gothic'; weight = 900 },
  @{ family = 'Noto Serif JP';   weight = 900 },
  @{ family = 'Dela Gothic One'; weight = 400 },
  @{ family = 'Yuji Syuku';      weight = 400 }
)
$ua = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0 Safari/537.36'
$chunk = 200   # characters per request (keeps the URL short); each chunk becomes its own @font-face
$css = New-Object Text.StringBuilder
[void]$css.AppendLine('/* Generated by tools/offline/fetch-offline.ps1 - do not edit by hand. */')
[void]$css.AppendLine('/* Fonts: SIL Open Font License 1.1 (see assets/fonts/LICENSE.txt) */')
foreach ($f in $fonts) {
  $slug = ($f.family.ToLower() -replace ' ', '-') + '-' + $f.weight
  $axis = if ($f.weight -eq 400 -and $f.family -ne 'Zen Maru Gothic') { '' } else { ":wght@$($f.weight)" }
  $n = 0
  for ($i = 0; $i -lt $chars.Count; $i += $chunk) {
    $part = $chars[$i..([Math]::Min($i + $chunk, $chars.Count) - 1)]
    $str = -join ($part | % { [char]$_ })
    $url = "https://fonts.googleapis.com/css2?family=$($f.family -replace ' ', '+')$axis&text=$([Uri]::EscapeDataString($str))"
    $face = (Invoke-WebRequest $url -UserAgent $ua -UseBasicParsing).Content
    $m = [regex]::Match($face, 'url\((https://[^)]+)\)\s*format\(.woff2.\)')
    if (-not $m.Success) { throw "no woff2 for $($f.family) $($f.weight)" }
    $n++
    $file = "$slug-$n.woff2"
    Invoke-WebRequest $m.Groups[1].Value -OutFile (Join-Path $fontDir $file) -UseBasicParsing
    $range = ($part | % { 'U+{0:X}' -f $_ }) -join ','
    [void]$css.AppendLine("@font-face{font-family:'$($f.family)';font-style:normal;font-weight:$($f.weight);font-display:swap;src:url(../assets/fonts/$file) format('woff2');unicode-range:$range}")
  }
  $size = (Get-ChildItem $fontDir -Filter "$slug-*.woff2" | Measure-Object Length -Sum).Sum
  Write-Host "ok  $($f.family) $($f.weight): $n files, $size bytes"
}
[IO.File]::WriteAllText((Join-Path $root 'css\fonts.css'), $css.ToString(), $utf8)
Write-Host 'ok  css/fonts.css'

# ---------- font licenses (OFL requires the license to travel with the fonts) ----------
$lic = New-Object Text.StringBuilder
foreach ($d in @(@('Zen Maru Gothic','zenmarugothic'), @('Noto Serif JP','notoserifjp'), @('Dela Gothic One','delagothicone'), @('Yuji Syuku','yujisyuku'))) {
  $t = (Invoke-WebRequest "https://raw.githubusercontent.com/google/fonts/main/ofl/$($d[1])/OFL.txt" -UseBasicParsing).Content
  [void]$lic.AppendLine("==================== $($d[0]) ====================").AppendLine($t.Trim()).AppendLine()
}
[IO.File]::WriteAllText((Join-Path $fontDir 'LICENSE.txt'), $lic.ToString(), $utf8)
Write-Host 'ok  assets/fonts/LICENSE.txt'
